"""Regenerate graphs/thanos_campaign.ttl from build_machine().

Structural triples are derived from the Python ESM. Research commentary,
PROV sources, exogenous Xandar activity, trajectories, and proposed
``tsm:unlockedBy`` links are layered on top so the ontology twin stays
executable-true without losing the stress-test findings.
"""

from __future__ import annotations

from pathlib import Path

from thanos_state_machine.campaign import build_machine
from thanos_state_machine.machine import ActionKind, Phase

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "graphs" / "thanos_campaign.ttl"

HEADER = """\
# Thanos campaign expressed in the CaseNoesis trajectory vocabulary.
#
# Deliberately does NOT use uco-observable / case-investigation classes:
# this is a fictional kinetic campaign, and the point of the exercise is
# that the traj: layer alone should carry it. Where it can't, that is a
# finding — see docs/ONTOLOGY.md.
#
# GENERATED by scripts/export_ttl.py from build_machine().
# Do not hand-edit structural states/actions/transitions; re-run the
# exporter. Parity is enforced by tests/test_ttl_parity.py.
#
# Source material (prov:wasDerivedFrom): Avengers: Infinity War (2018),
# Avengers: Endgame (2019). No day-level times are fabricated; intervals
# are film-scoped.

@prefix traj: <https://casenoesis.org/ontology/trajectory#> .
@prefix tsm:  <https://github.com/mrinaalr/ThanosStateMachine#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
"""

STATE_COMMENTS = {
    "SnapEvent": (
        "Terminal harm event of the 2018 trajectory; interior state of "
        "the 2018-2023 composite trajectory."
    ),
    "GardenWithdrawal": (
        "Stone destruction as harm maintenance: making the completed "
        "harm irreversible."
    ),
    "LokiCoercion": "Hostage leverage: Thor's life against the Tesseract.",
    "GamoraLeverage": (
        "Affordance accumulation: Reality Stone (prior extraction) defeats "
        "Gamora's suicide attempt."
    ),
    "StrangeBargain": (
        "Hostage leverage: Stark's life against the Eye of Agamotto."
    ),
    "MindExtraction": (
        "Affordance accumulation: Time Stone reverses the Mind Stone's "
        "destruction."
    ),
}

TRANSITION_COMMENTS = {
    ("GamoraLeverage", "SoulExtraction"): (
        "Edge labelled by an affordance unlocked in a SIBLING layer: the "
        "layered extension permits this; nothing in traj: requires A to be "
        "static."
    ),
}

# Proposed vocab extension (docs/ONTOLOGY.md): affordance -> extraction
# that unlocked it. Emitted as tsm:unlockedBy pending CaseNoesis upstream.
UNLOCKED_BY = {
    "a_space_skip": "SpaceExtraction",
    "a_reality_warp": "RealityExtraction",
    "a_time_reverse": "TimeExtraction",
}

PROV_IW = {
    ("CampaignInitiation", "StatesmanIntercept"),
    ("MindExtraction", "SnapEvent"),
}
PROV_EG = {
    ("SnapEvent", "GardenWithdrawal"),
    ("GardenWithdrawal", "RemediationBattle"),
    ("RemediationBattle", "CampaignRemediated"),
}


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _ttl_state(name: str, phase: Phase | None, layer: str | None) -> str:
    bits = [f"tsm:{name} a traj:State"]
    preds: list[str] = []
    if phase is not None:
        preds.append(f'traj:phaseLabel "{phase.value}"')
    if layer is not None:
        preds.append(f'traj:layer "{layer}"')
    if name in STATE_COMMENTS:
        preds.append(f'rdfs:comment "{_esc(STATE_COMMENTS[name])}"')
    if preds:
        return bits[0] + " ;\n    " + " ; ".join(preds) + " .\n"
    return bits[0] + " .\n"


def _ttl_action(name: str, kind: ActionKind, description: str) -> str:
    preds = [f'rdfs:label "{_esc(description)}"']
    if kind is ActionKind.AFFORDANCE:
        preds.insert(0, "tsm:affordance true")
    if kind is ActionKind.INTERVENTION:
        preds.insert(0, "tsm:guardianIntervention true")
    if name in UNLOCKED_BY:
        preds.append(f"tsm:unlockedBy tsm:{UNLOCKED_BY[name]}")
    return f"tsm:{name} a traj:Action ; " + " ; ".join(preds) + " .\n"


def _edge_id(i: int, source: str, target: str) -> str:
    return f"t-{i:02d}-{source}-to-{target}"


def to_ttl() -> str:
    m = build_machine()
    lines = [HEADER, ""]

    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Source documents")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append('tsm:src-infinity-war a prov:Entity ;')
    lines.append('    rdfs:label "Avengers: Infinity War (2018), Marvel Studios" .')
    lines.append("")
    lines.append("tsm:src-endgame a prov:Entity ;")
    lines.append('    rdfs:label "Avengers: Endgame (2019), Marvel Studios" .')
    lines.append("")

    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Exogenous prior acquisition (mirrors elder_scheme.ttl)")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("tsm:activity-xandar a prov:Activity ;")
    lines.append('    rdfs:label "Power Stone acquisition (Xandar); exogenous, pre-s0" ;')
    lines.append("    prov:wasDerivedFrom tsm:src-infinity-war .")
    lines.append("")

    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# States")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    # Stable order: campaign spine first, then stone layers as in machine insert order
    for name, state in m.states.items():
        lines.append(_ttl_state(name, state.phase, state.layer))

    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Actions / affordances")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    for name, action in m.actions.items():
        lines.append(_ttl_action(name, action.kind, action.description))

    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Transitions — derived 1:1 from build_machine()")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    for i, t in enumerate(m.transitions, start=1):
        eid = _edge_id(i, t.source, t.target)
        preds = [
            f"traj:fromState tsm:{t.source}",
            f"traj:toState tsm:{t.target}",
        ]
        if t.actions:
            acts = ", ".join(f"tsm:{a}" for a in t.actions)
            preds.append(f"traj:enactsAction {acts}")
        if t.trigger:
            preds.append(f'traj:trigger "{_esc(t.trigger)}"')
        key = (t.source, t.target)
        if key in TRANSITION_COMMENTS:
            preds.append(f'rdfs:comment "{_esc(TRANSITION_COMMENTS[key])}"')
        if key in PROV_IW:
            preds.append("prov:wasDerivedFrom tsm:src-infinity-war")
        if key in PROV_EG:
            preds.append("prov:wasDerivedFrom tsm:src-endgame")
        lines.append(f"tsm:{eid} a traj:Transition ;")
        for j, pred in enumerate(preds):
            end = " ." if j == len(preds) - 1 else " ;"
            lines.append(f"    {pred}{end}")
        lines.append("")

    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Trajectories")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("tsm:trajectory-2018 a traj:Trajectory ;")
    lines.append('    rdfs:label "Stone campaign through the Snap" ;')
    lines.append("    traj:terminalState tsm:SnapEvent ;")
    lines.append('    traj:terminalPolarity "completed" ;')
    lines.append("    prov:wasDerivedFrom tsm:src-infinity-war .")
    lines.append("")
    lines.append("tsm:trajectory-2018-2023 a traj:Trajectory ;")
    lines.append(
        '    rdfs:label "Stone campaign through the Snap, its maintenance, and its reversal" ;'
    )
    lines.append("    traj:terminalState tsm:CampaignRemediated ;")
    lines.append('    traj:terminalPolarity "remediated" ;')
    lines.append(
        '    rdfs:comment "STRESS FINDING: not expressible in the binary '
        "completed/disrupted range of traj:terminalPolarity. The harm state "
        "was reached AND subsequently reversed. Elder-scheme polarity assumes "
        "disruption happens before completion; this case falsifies that "
        'assumption at the vocabulary level." ;'
    )
    lines.append("    prov:wasDerivedFrom tsm:src-endgame .")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    TARGET.write_text(to_ttl())
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
